### ISSUE TITLE
Use of undefined constant CURL_SSLVERSION_TLSv1_2

### ISSUE THREAD

**Issue by rmullaney77** [wepay/PHP-SDK#26]
Very easy fix for PHP versions prior to CURL_SSLVERSION_TLSv1_2 constant being available...

somewhere before...

`curl_setopt(self::$ch, CURLOPT_SSLVERSION, CURL_SSLVERSION_TLSv1_2);`

executes, add...
```
if ( ! defined('CURL_SSLVERSION_TLSv1_2')) {
	define('CURL_SSLVERSION_TLSv1_2', 6);
}
```

**Comment by skyzyx** [comment]
We decided to add this logic intentionally. We only _officially_ support PHP 5.5.19/5.6.3 or higher + the paired PHP cURL extension, where this constant exists. Any versions of PHP older than this are EOL anyway.

PCI-DSS 3.x rules dictate that TLS 1.0 and 1.1 are no longer considered _secure_, so all communication needs to happen over TLS 1.2 or newer. The hard deadline for this switchover is June 2018, but WePay has been working with customers over the last year to get everybody migrated to a technology stack which supports TLS 1.2 natively.

As such, adding this logic runs counter to the direction that the payments industry needs to move in, in order to meet the updated PCI-DSS guidelines. Also, it would only be necessary for versions of PHP which are officially unsupported by both the PHP Core team and WePay.

_(Disclosure: I am a former engineer for WePay, and was the one who wrote this code and added this logic to the SDK after discussions with our Director of Security. While I can no longer speak for WePay in an official capacity, I am uniquely qualified to speak about this particular issue.)_

**Comment by rmullaney77** [comment]
Adding a missing constant for prior older PHP versions where TLS1.2 is
present is not counter to PCI-DSS goals.

Doesn't matter to me, was a 10 second fix where an undefined constant was
the ONLY compatibility issue.

**Comment by matthewclower** [comment]
@rmullaney77,

Per PCI-DSS we require all new implementations use at least TLS 1.2 and though we appreciate your suggestion we are unable to make this change.

By defining the constant manually the interpreter is able to proceed without error but the connection that results is not TLS 1.2 unless the extension also supports it. Defining the constant if it does not exist is not sufficient and connections not using at least TLS 1.2 will be rejected once support for TLS versions below 1.2 has been fully deprecated by WePay.

TLS 1.2 is available via the PHP cURL extension as of version 7.34.0 of cURL and you can check your support like this:

```php
<?php
echo ' PHP version: ' . phpversion() . PHP_EOL;
echo 'cURL version: ' . curl_version()['version'] . PHP_EOL;

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://www.howsmyssl.com/a/check");
curl_setopt($ch, CURLOPT_SSLVERSION, 6);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$response = curl_exec($ch);
curl_close($ch);

echo ' TLS version: ' . json_decode($response)->tls_version . PHP_EOL;
```

**NOTE** that it is now possible to open connections using TLS 1.2 in earlier versions of PHP:

```bash
$php54 curl_test.php 
 PHP version: 5.4.45
cURL version: 7.50.3
 TLS version: TLS 1.2
```
